version: '2'
services:
  application:
    build: docker/application
    networks:
      - app_net
    volumes:
      - ./:/var/www

  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - application
    networks:
      - app_net
    volumes_from:
      - application

# @TODO make sure you enable mongodb auth for security reasons
  mongodb:
    image: mongo:latest
    networks:
      - app_net
    volumes:
      - ./docker/mongodb/data:/data/db

networks:
  app_net:
    driver: bridge
