web:
    resource: "@PegWebBundle/Resources/config/routing.yml"
    prefix:   /

api:
  resource: "@PegApiBundle/Resources/config/routing.yml"
  prefix:   /

overblog_graphql_endpoint:
  resource: "@OverblogGraphQLBundle/Resources/config/routing/graphql.yml"
  prefix: /graphql
