fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

overblog_graphql_endpoint:
  path: /graphql/
  defaults:
      _controller: OverblogGraphQLBundle:Graph:endpoint
  options:
      expose: true

web:
    resource: "@PegWebBundle/Resources/config/routing.yml"
    prefix:   /

api:
  resource: "@PegApiBundle/Resources/config/routing.yml"
  prefix:   /