<?php

namespace Peg\Bundles\ApiBundle\Repository\Doctrine\ODM;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Peg\Bundles\ApiBundle\Document\CommentEvent;
use Peg\Bundles\ApiBundle\Document\Peg;
use Peg\Repository\CommentEventRepositoryInterface;

/**
 * CommentEventRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class CommentEventRepository extends DocumentRepository implements CommentEventRepositoryInterface
{
    /**
     * @param Peg $peg
     *
     * @return CommentEvent[]|array
     */
    public function findAllForPeg(Peg $peg):array
    {
        return $this->findBy(['peg' => $peg]);
    }


    public function save(CommentEvent $event, $sync = true)
    {
        $this->dm->persist($event);

        if ($sync === true) {
            $this->dm->flush($event);
        }
    }
}
