<?php

namespace Peg\Bundles\ApiBundle\Repository\Doctrine\ODM;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Peg\Bundles\ApiBundle\Document\LocationEvent;
use Peg\Bundles\ApiBundle\Document\Peg;
use Peg\Repository\LocationEventRepositoryInterface;

/**
 * LocationEventRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class LocationEventRepository extends DocumentRepository implements LocationEventRepositoryInterface
{
    /**
     * @param Peg $peg
     *
     * @return LocationEvent[]|array
     */
    public function findAllForPeg(Peg $peg): array
    {
        return $this->findBy(['peg' => $peg]);
    }


    public function save(LocationEvent $event, $sync = true)
    {
        $this->dm->persist($event);

        if ($sync === true) {
            $this->dm->flush($event);
        }
    }
}
