<?php

namespace Peg\Bundles\ApiBundle\Repository\Doctrine\ODM;

use Doctrine\ODM\MongoDB\DocumentManager;
use Peg\Bundles\ApiBundle\Document\PictureEvent;
use Peg\Repository\PictureEventRepositoryInterface;

/**
 * PictureEventRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class PictureEventRepository implements PictureEventRepositoryInterface
{
    /**
     * @var DocumentManager
     */
    private $documentManager;

    /**
     * @param DocumentManager $documentManager
     */
    public function __construct(DocumentManager $documentManager)
    {
        $this->documentManager = $documentManager;
    }

    public function save(PictureEvent $event, $sync = true)
    {
        $this->documentManager->persist($event);

        if ($sync === true) {
            $this->documentManager->flush($event);
        }
    }
}
