services:
  peg.api.resolver.peg:
    class: Peg\Bundles\ApiBundle\GraphQL\Mutation\PegMutation
    arguments:
      - "@tactician.commandbus"
      - "@peg.util.short_code_generator"
    tags:
      - { name: overblog_graphql.mutation, alias: "peg_mutation_create", method: "createPeg" }

  peg.api.resolver.peg_location_event:
    class: Peg\Bundles\ApiBundle\GraphQL\Mutation\PegLocationEventMutation
    arguments:
      - "@tactician.commandbus"
    tags:
      - { name: overblog_graphql.mutation, alias: "peg_location_event_mutation_create", method: "createPegLocationEvent" }

  peg.api.resolver.comment:
    class: Peg\Bundles\ApiBundle\GraphQL\Mutation\CommentMutation
    arguments:
      - "@tactician.commandbus"
    tags:
      - { name: overblog_graphql.mutation, alias: "comment_mutation_create", method: "createComment" }
