imports:
    - { resource: "@PegApiBundle/Resources/config/graphql.resolvers.yml" }
    - { resource: "@PegApiBundle/Resources/config/graphql.mutations.yml" }

services:
    peg.api_bundle.repository.doctrine.odm.peg:
        class: Peg\Bundles\ApiBundle\Repository\Doctrine\ODM\PegRepository
        factory: ['@doctrine.odm.mongodb.document_manager', getRepository]
        arguments:
            - Peg\Bundles\ApiBundle\Document\Peg

    peg.util.short_code_generator:
        class: Peg\Util\ShortCodeGenerator
        arguments:
            - '@peg.api_bundle.repository.doctrine.odm.peg'