- name: clean old containers and images with docker-custodian
  shell: docker run -it -v /var/run/docker.sock:/var/run/docker.sock yelp/docker-custodian dcgc --max-container-age 3days --max-image-age 7days
  ignore_errors: yes