---
- name: create directory for docker credentials for the root user
  file:
    dest=/root/.docker
    state=directory
    recurse=true
    mode=766

- name: install docker hub credentials for docker for the root user
  copy:
    src=dockercfg.json
    dest=/root/.docker/config.json

- name: create directory for docker credentials for the ubuntu user
  file:
    dest=/home/ubuntu/.docker
    state=directory
    recurse=true
    mode=766
    owner=ubuntu
    group=ubuntu

- name: install docker hub credentials for docker for the ubuntu user
  copy:
    src=dockercfg.json
    dest=/home/ubuntu/.docker/config.json
    owner=ubuntu
    group=ubuntu
