services:
  peg.persistence.command.peg_create.handler:
    class: Peg\Domain\Commands\PegCreateHandler
    arguments:
      - "@doctrine.odm.mongodb.document_manager"
    tags:
      - { name: tactician.handler, command: Peg\Domain\Commands\PegCreate }

  peg.persistence.command.update_location.handler:
    class: Peg\Domain\Commands\UpdateLocationHandler
    arguments:
      - "@peg.api_bundle.repository.doctrine.odm.peg"
      - "@peg.api_bundle.repository.doctrine.odm.location_event"
    tags:
      - { name: tactician.handler, command: Peg\Domain\Commands\UpdateLocation }

  peg.persistence.command.add_comment.handler:
    class: Peg\Domain\Commands\AddCommentHandler
    arguments:
      - "@peg.api_bundle.repository.doctrine.odm.peg"
      - "@peg.api_bundle.repository.doctrine.odm.comment_event"
    tags:
      - { name: tactician.handler, command: Peg\Domain\Commands\AddComment }

  peg.persistence.command.add_picture.handler:
    class: Peg\Domain\Commands\AddPictureHandler
    arguments:
      - "@peg.api_bundle.repository.doctrine.odm.peg"
      - "@peg.api_bundle.repository.doctrine.odm.picture_event"
    tags:
      - { name: tactician.handler, command: Peg\Domain\Commands\AddPicture }
