web_homepage:
    path:     /
    defaults: { _controller: PegWebBundle:Default:index }
    options:
        expose: true

web_timeline:
    path:     /{shortcode}
    defaults: { _controller: PegWebBundle:Default:timeline }
    options:
        expose: true
