PegEvent:
  type: object
  config:
    description:  "Give a comment on a peg event"
    fields:
      id:
        type:         "String!"
        description:  "The ID of this comment"
      comment:
        type:         "String"
        description:  "The comment itself"
      user:
        type:         "User"
        description:  "Who did it"
        resolve: "@=resolver('user_by_id', [value['user_id']])"
      happenedAt:
        type:         "String"
        description:  "When this happened"
