Mutation:
  type: object
  config:
    fields:
      createPeg:
        type: "Peg"
        resolve: "@=mutation('peg_mutation_create')"
      createPegLocationEvent:
        type: "PegLocationEvent"
        args:
          location:
            type: "String!"
        resolve: "@=mutation('peg_location_event_mutation_create', args['location'])"
      createComment:
        type: Query
        resolve: "@=mutation('comment_mutation_create')"
