Mutation:
  type: object
  config:
    fields:
      createPeg:
        type: Query
        resolve: "@=mutation('peg_mutation_create')"
      createPegEvent:
        type: Query
        resolve: "@=mutation('peg_event_mutation_create')"
      createComment:
        type: Query
        resolve: "@=mutation('comment_mutation_create')"
