# This implements the following type system shorthand:
#   interface Peg {
#     id: String!
#     shortcode: String
#   }
Peg:
  type: object
  config:
    description:  "You know… a clothes peg!"
    fields:
      id:
        type:         "String!"
        description:  "The ID of the peg"
      shortcode:
        type:         "String"
        description:  "Shortcode used to access the peg"
      pegEvents:
        # @todo Add Pagination
        type: "[PegEvent]"
        description: "Ohhh.. what happened to me?!"
        resolve: "@=resolver('peg_events', [value])"
      createPegLocationEvent:
        type: "PegEvent"
        args:
          location:
            type: "String!"
        resolve: "@=mutation('peg_location_event_mutation_create', [value, args['location']])"
