PegCommentEvent:
  type: object
  config:
    description:  "You know… a peg with a comment"
    fields:
      id:
        type:         "String!"
        description:  "The ID of this event"
      comment:
        type:         "String"
        description:  "the content of the comment"
      description:
        type:         "String"
        description:  "the description of the event"
      location:
        type:         "String!"
        description:  "and what was the location"
