PegEvent:
  type: object
  config:
    description:  "You know… a peg do stuff"
    fields:
      id:
        type:         "String!"
        description:  "The ID of this event"
      type:
        type:         "String"
        description:  "Event type"
      description:
        type:         "String"
        description:  "What is this event"
      location:
        type:         "String"
        description:  "and what was the location"
      comment:
        type:         "String"
        description:  "you know...stuff you said"
      happenedAt:
        type:         "String"
        description:  "When it happened, rights?"
