PegLocationEvent:
  type: object
  config:
    description:  "You know… a peg do stuff"
    fields:
      id:
        type:         "String!"
        description:  "The ID of this event"
      description:
        type:         "String"
        description:  "What is this event"
      location:
        type:         "String!"
        description:  "and what was the location"
      comment:
        type:         "String"
        description:  "the content of the comment"
