Query:
  type: object
  config:
    description: "Some pegs"
    fields:
      pegs:
        type: "[Peg]"
        resolve: "@=resolver('pegs')"
      peg:
        type: "Peg"
        resolve: "@=resolver('peg', [args['shortcode']])"
        args:
          shortcode:
            type: "String!"
      users:
        type: "[User]"
        resolve: "@=resolver('users')"
      user:
        type: "User"
        args:
          email:
            type: "String!"
        resolve: "@=resolver('user', [args['email']])"
